### ISSUE TITLE
[Code Addition Request]: Blockchain Voting System

### ISSUE THREAD

**Issue by dino65-dev** [UTSAVS26/PyVerse#1038] opened 2024-11-03 09:00 UTC
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/780

## Blockchain-Based Voting System
The Blockchain-Based Voting System is an innovative and secure platform designed to facilitate transparent and immutable voting processes using blockchain technology. This project leverages smart contracts on the Ethereum  blockchain to ensure that each vote is recorded accurately and cannot be tampered with, providing a high level of trust and security in the electoral process.
### Features
---
- Secure Voting: Utilizes blockchain technology to ensure that all votes are securely recorded and immutable.
- Smart Contract Management: Implements smart contracts to handle candidate registration, voting, and vote tallying.
- User Authentication: Integrates with MetaMask  for secure user authentication and transaction signing.

### Full Name

Dinmay Kumar Brahma

### Participant Role

- ### HACKTOBERFEST
-  ### GSSOC - EXT 2024
- ### CONTRIBUTOR

**Comment by UTSAVS26** [comment] 2024-11-03 13:39
@dino65-dev don't raise any PR until the issue is assigned to you.

**Closed** 2024-11-03 13:39 UTC
Labels: gssoc-ext
