### ISSUE TITLE
[Code Addition Request]: Jarvis-Desktop-Voice-Assistant

### ISSUE THREAD

**Issue by devxMani** [UTSAVS26/PyVerse#861] opened 2024-10-26 14:10 UTC
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

 Jarvis-Desktop-Voice-Assistant

### Full Name

Mani

### Participant Role

GSSOC ext 24

**Comment by UTSAVS26** [comment] 2024-10-27 04:23
@devxMani don't raise PR until the issue is assigned to you.

**Closed** 2024-10-27 04:23 UTC
